/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Json = string;
export type PreferenceKey = string;
export type PreferenceValue = string;
export type Symbol = string;
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[Symbol], undefined>,
  'clearPreferences' : ActorMethod<[], undefined>,
  'clearWatchlist' : ActorMethod<[], undefined>,
  'getAllPreferences' : ActorMethod<
    [],
    Array<[PreferenceKey, PreferenceValue]>
  >,
  'getExecutionStateSnapshot' : ActorMethod<[Symbol], Json>,
  'getPreference' : ActorMethod<[PreferenceKey], PreferenceValue>,
  'getUserPreferences' : ActorMethod<[], Json>,
  'getWatchlist' : ActorMethod<[], Array<Symbol>>,
  'removeExecutionStateSnapshot' : ActorMethod<[Symbol], undefined>,
  'removeFromWatchlist' : ActorMethod<[Symbol], undefined>,
  'saveExecutionStateSnapshot' : ActorMethod<[Symbol, Json], undefined>,
  'saveUserPreferences' : ActorMethod<[Json], undefined>,
  'setPreference' : ActorMethod<[PreferenceKey, PreferenceValue], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];