/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Symbol = IDL.Text;
export const PreferenceKey = IDL.Text;
export const PreferenceValue = IDL.Text;
export const Json = IDL.Text;

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([Symbol], [], []),
  'clearPreferences' : IDL.Func([], [], []),
  'clearWatchlist' : IDL.Func([], [], []),
  'getAllPreferences' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PreferenceKey, PreferenceValue))],
      ['query'],
    ),
  'getExecutionStateSnapshot' : IDL.Func([Symbol], [Json], ['query']),
  'getPreference' : IDL.Func([PreferenceKey], [PreferenceValue], ['query']),
  'getUserPreferences' : IDL.Func([], [Json], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(Symbol)], ['query']),
  'removeExecutionStateSnapshot' : IDL.Func([Symbol], [], []),
  'removeFromWatchlist' : IDL.Func([Symbol], [], []),
  'saveExecutionStateSnapshot' : IDL.Func([Symbol, Json], [], []),
  'saveUserPreferences' : IDL.Func([Json], [], []),
  'setPreference' : IDL.Func([PreferenceKey, PreferenceValue], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Symbol = IDL.Text;
  const PreferenceKey = IDL.Text;
  const PreferenceValue = IDL.Text;
  const Json = IDL.Text;
  
  return IDL.Service({
    'addToWatchlist' : IDL.Func([Symbol], [], []),
    'clearPreferences' : IDL.Func([], [], []),
    'clearWatchlist' : IDL.Func([], [], []),
    'getAllPreferences' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PreferenceKey, PreferenceValue))],
        ['query'],
      ),
    'getExecutionStateSnapshot' : IDL.Func([Symbol], [Json], ['query']),
    'getPreference' : IDL.Func([PreferenceKey], [PreferenceValue], ['query']),
    'getUserPreferences' : IDL.Func([], [Json], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(Symbol)], ['query']),
    'removeExecutionStateSnapshot' : IDL.Func([Symbol], [], []),
    'removeFromWatchlist' : IDL.Func([Symbol], [], []),
    'saveExecutionStateSnapshot' : IDL.Func([Symbol, Json], [], []),
    'saveUserPreferences' : IDL.Func([Json], [], []),
    'setPreference' : IDL.Func([PreferenceKey, PreferenceValue], [], []),
  });
};

export const init = ({ IDL }) => { return []; };